version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    target-branch: "libtorrent-master"
    directory: "/"
    schedule:
      interval: "daily"
  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    target-branch: "libtorrent-master"
    directory: "/"
    schedule:
      interval: "daily"
